
spring:
  application:
    name: eurka-server
  profiles:
    active: server2

---
spring:
  profiles: server1

server:
  port: 8761

eureka:
  instance:
    hostname: server1
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://server2:8762/eureka/


---
spring:
  profiles: server2

server:
  port: 8762

eureka:
  instance:
    hostname: server2
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://server1:8761/eureka/




